### ISSUE TITLE
Chrome intent error

### ISSUE THREAD

**Issue by enviro-apps** [aboutyou/dart_packages#210]
Hello, I have a problem. When the Apple Login is succesfully completed I get the following error:
```
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{app.lalamu.app/app.lalamu.app.SignInWithAppleCallback}: java.lang.ClassNotFoundException: Didn't find class "app.lalamu.app.SignInWithAppleCallback" on path: DexPathList[[zip file "/data/app/~~6IR8Q2xSa0X57ta4fiXYKA==/app.lalamu.app-4cwmJXS8EbQmm40sE9EdZQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~6IR8Q2xSa0X57ta4fiXYKA==/app.lalamu.app-4cwmJXS8EbQmm40sE9EdZQ==/lib/x86, /data/app/~~6IR8Q2xSa0X57ta4fiXYKA==/app.lalamu.app-4cwmJXS8EbQmm40sE9EdZQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
E/AndroidRuntime( 2296): Caused by: java.lang.ClassNotFoundException: Didn't find class "app.lalamu.app.SignInWithAppleCallback" on path: DexPathList[[zip file "/data/app/~~6IR8Q2xSa0X57ta4fiXYKA==/app.lalamu.app-4cwmJXS8EbQmm40sE9EdZQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~6IR8Q2xSa0X57ta4fiXYKA==/app.lalamu.app-4cwmJXS8EbQmm40sE9EdZQ==/lib/x86, /data/app/~~6IR8Q2xSa0X57ta4fiXYKA==/app.lalamu.app-4cwmJXS8EbQmm40sE9EdZQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib, /product/lib]] 
E/AndroidRuntime( 2296): at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207) 
E/AndroidRuntime( 2296): at java.lang.ClassLoader.loadClass(ClassLoader.java:379) 
E/AndroidRuntime( 2296): at java.lang.ClassLoader.loadClass(ClassLoader.java:312) 
E/AndroidRuntime( 2296): at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95) 
E/AndroidRuntime( 2296): at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45) 
E/AndroidRuntime( 2296): at android.app.Instrumentation.newActivity(Instrumentation.java:1253) 
E/AndroidRuntime( 2296): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353) 
E/AndroidRuntime( 2296): ... 11 more 
I/Process ( 2296): Sending signal. PID: 2296 SIG: 9
```

My Manifest looks like this:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="app.lalamu.app">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="Lalamu"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name="app.lalamu.app.SignInWithAppleCallback"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="signinwithapple" />
                <data android:path="callback" />
            </intent-filter>
        </activity>
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            andr
oid:value="2" />
    </application>
</manifest>
```

I am Using your Glitch server example and this is how I do the Intent:

app.post("/callbacks/sign_in_with_apple", (request, response) => {
  const redirect = `intent://callback?${new URLSearchParams(
    request.body
  ).toString()}#Intent;package=app.lalamu.app;scheme=signinwithapple;end`;

  console.log(`Redirecting to ${redirect}`);

  response.redirect(307, redirect);
});

Am I doing something wrong?

Any help is appreciated
Best Regards

**Comment by enviro-apps** [comment]
Ok I solved it the problem was I added my package name to the activty instead of yours as in the demo
