### ISSUE TITLE
Pop up for entering credentials for apple login disappears immediately in flutter web

### ISSUE THREAD

**Issue by flutterwithfaiz** [aboutyou/dart_packages#284]
Sign in with apple is working in debug mode but when I deploy my flutter web app on firebase and tried to get logged in using apple credentials, pop up immediately disappeared when I clicked Login button.

**Comment by HenriBeck** [comment]
@flutterwithfaiz do you see any errors in the network tab or console?

**Comment by Moumene** [comment]
Can you please tell me what did you do to make it in your side @flutterwithfaiz ? 
I m getting an UNKOWN_SIWA_ERROR when trying the web version.

**Comment by chadlyalan** [comment]
> Can you please tell me what did you do to make it in your side @flutterwithfaiz ? I m getting an UNKOWN_SIWA_ERROR when trying the web version.

Hey I'm getting the same issue when debugging. 
When I host on firebase I get: "Uncaught Unsupported operation: Platform._operatingSystem"
Did you find a solution to your issue?
I have gone over the set up process a few times now and I'm pretty confident I followed each steps for setting up web configuration.

**Comment by nrajput05** [comment]
Got the same issue as well. On local the popup comes up fine but once deployed no popup at all and the error in console is:
```
main.dart.js:4962 Uncaught Unsupported operation: Platform._operatingSystem
    at Object.c (https://sit.billwallet.com/main.dart.js:4962:19)
    at Object.bfM (https://sit.billwallet.com/main.dart.js:33079:15)
    at Object.bfO (https://sit.billwallet.com/main.dart.js:33081:16)
    at https://sit.billwallet.com/main.dart.js:118267:23
    at a.<computed> [as aSJ] (https://sit.billwallet.com/main.dart.js:32:36)
    at https://sit.billwallet.com/main.dart.js:118270:24
    at a.<computed> [as b51] (https://sit.billwallet.com/main.dart.js:32:36)
    at https://sit.billwallet.com/main.dart.js:109541:38
    at aR8.a (https://sit.billwallet.com/main.dart.js:6315:62)
    at aR8.$2 (https://sit.billwallet.com/main.dart.js:47285:14)
```
    
This is how I am setting the redirect Uri:

```
Uri get appleRedirectURI {
    if (kIsWeb) {
      //return Uri.parse('https://${window.location.host}/');
      return Uri.parse(appEnvironment.baseURL);
    } else {
      //For android
      return Uri.parse('https://foobar.com/callbacks/sign_in_with_apple');
    }
  }
```
