### ISSUE TITLE
Redirect back to android app exception

### ISSUE THREAD

**Issue by dndeus** [aboutyou/dart_packages#321]
Hi sir, 

When the glitch app redirect with intent back to android app I'm getting this exception, 
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.app/com.aboutyou.dart_packages.sign_in_with_apple.SignInWithAppleCallback}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData(android.content.Context)' on a null object reference
E/AndroidRuntime( 7607): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3686)
E/AndroidRuntime( 7607): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3823)
E/AndroidRuntime( 7607): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/AndroidRuntime( 7607): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 7607): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 7607): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
E/AndroidRuntime( 7607): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 7607): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 7607): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 7607): 	at android.app.ActivityThread.main(ActivityThread.java:7892)
E/AndroidRuntime( 7607): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7607): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 7607): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime( 7607): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData(android.content.Context)' on a null object reference
E/AndroidRuntime( 7607): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1799)
E/AndroidRuntime( 7607): 	at android.app.Activity.startActivityForResult(Activity.java:5470)
E/AndroidRuntime( 7607): 	at android.app.Activity.startActivityForResult(Activity.java:5428)
E/AndroidRuntime( 7607): 	at android.app.Activity.startActivity(Activity.java:5926)
E/AndroidRuntime( 7607): 	at android.app.Activity.startActivity(Activity.java:5893)
E/AndroidRuntime( 7607): 	at com.aboutyou.dart_packages.sign_in_with_apple.SignInWithApplePlugin$onMethodCall$1.invoke(SignInWithApplePlugin.kt:89)
E/AndroidRuntime( 7607): 	at com.aboutyou.dart_packages.sign_in_with_apple.SignInWithApplePlugin$onMethodCall$1.invoke(SignInWithApplePlugin.kt:84)
E/AndroidRuntime( 7607): 	at com.aboutyou.dart_packages.sign_in_with_apple.SignInWithAppleCallback.onCreate(SignInWithApplePlugin.kt:168)
E/AndroidRuntime( 7607): 	at android.app.Activity.performCreate(Activity.java:8285)
E/AndroidRuntime( 7607): 	at android.app.Activity.performCreate(Activity.java:8264)
E/AndroidRuntime( 7607): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
E/AndroidRuntime( 7607): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3667)
```

I have updated the `AndroidManifest.xml` with the activity snippet you provide in the documentation, just to let you know my app is not on the google play store yet, I'm currently building it so I haven't upload any apks yet if that helps. 

The `com.example.app` shown above is just a place holder package name. I have the right one in the `AndroidManifest.xml`.

Any suggestions? 

Thank you for your efforts

**Comment by HenriBeck** [comment]
@dndeus can you please provide information about which Android version this is, which manufacturer, and your Flutter doctor output?

**Comment by sernocturno** [comment]
here the same, im using android 10

**Comment by HenriBeck** [comment]
Closing due to inactivity
