### ISSUE TITLE
example: android.content.ActivityNotFoundException

### ISSUE THREAD

**Issue by rounce** [aboutyou/dart_packages#380]
Steps to reproduce:
1. run example (sign_in_with_apple 5.0.0)
2. tap to "Sign In with Apple" button
```
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861): Failed to handle method call
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://appleid.apple.com/... (has extras) }
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861):   at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861):   at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861):   at android.app.Activity.startActivityForResult(Activity.java:5314)
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861):   at com.aboutyou.dart_packages.sign_in_with_apple.SignInWithApplePlugin.onMethodCall(SignInWithApplePlugin.kt:96)
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861):   at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861):   at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861):   at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861):   at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861):   at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861):   at android.os.Looper.loop(Looper.java:223)
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861):   at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861):   at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#com.aboutyou.dart_packages.sign_in_with_apple( 3861):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
D/AndroidRuntime( 3861): Shutting down VM
E/AndroidRuntime( 3861): FATAL EXCEPTION: main
E/AndroidRuntime( 3861): Process: com.aboutyou.dart_packages.sign_in_with_apple.example, PID: 3861
E/AndroidRuntime( 3861): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=0, data=null} to activity {com.aboutyou.dart_packages.sign_in_with_apple.example/com.aboutyou.dart_packages.sign_in_with_apple.example.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 3861):        at android.app.ActivityThread.deliverResults(ActivityThread.java:5015)
E/AndroidRuntime( 3861):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
E/AndroidRuntime( 3861):        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 3861):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 3861):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 3861):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime( 3861):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 3861):        at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 3861):        at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 3861):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3861):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 3861):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime( 3861): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 3861):        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime( 3861):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:268)
E/AndroidRuntime( 3861):        at com.aboutyou.dart_packages.sign_in_with_apple.SignInWithApplePlugin.onActivityResult(SignInWithApplePlugin.kt:131)
E/AndroidRuntime( 3861):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:809)
E/AndroidRuntime( 3861):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:432)
E/AndroidRuntime( 3861):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:872)
E/AndroidRuntime( 3861):        at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:917)
E/AndroidRuntime( 3861):        at android.app.Activity.dispatchActivityResult(Activity.java:8304)
E/AndroidRuntime( 3861):        at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
E/AndroidRuntime( 3861):        ... 11 more
E/flutter ( 3861): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: UnknownSignInWithAppleException(error, No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://appleid.apple.com/... (has extras) }, null)
E/flutter ( 3861): #0      MethodChannelSignInWithApple._signInWithAppleAndroid (package:sign_in_with_apple_platform_interface/method_channel_sign_in_with_apple.dart:194:7)
E/flutter ( 3861): <asynchronous suspension>
E/flutter ( 3861): #1      _MyAppState.build.<anonymous closure> (package:sign_in_with_apple_example/main.dart:44:36)
E/flutter ( 3861): <asynchronous suspension>
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.5, on Manjaro Linux 6.1.31-2-MANJARO, locale ru_RU.UTF-8)
    • Flutter version 3.10.5 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 недели назад), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
    • Android SDK at /opt/android-sdk
    • Platform android-33, build-tools 34.0.0-rc2
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.26.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      • Manjaro Linux 6.1.31-2-MANJARO
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by rounce** [comment]
It looks like it's some kind of emulator issue.
