### ISSUE TITLE
sign_in_with_apple: MISSING_ACTIVITY on android

### ISSUE THREAD

**Issue by Dreamersoul** [aboutyou/dart_packages#85]
Hello, the plugin works perfectly on iOS for me however i added the web parameters
```dart
await SignInWithApple.getAppleIDCredential(
    scopes: [
        AppleIDAuthorizationScopes.email,
        AppleIDAuthorizationScopes.fullName,
     ],
    webAuthenticationOptions: WebAuthenticationOptions(
    clientId: "com.example.app",
    redirectUri: Uri.parse("https://${Constants.BASE_HOST}/user/auth/apple/callback")
);
```
however when clicking on the button i get the following error:
```logcat
2020-05-26 16:45:26.864 7062-7114/com.exampe.app E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(MISSING_ACTIVITY, Plugin is not attached to an activity, {url: https://appleid.apple.com/auth/authorize?client_id=com.example.app&redirect_uri=https%3A%2F%2Fexample.herokuapp.com%2Fuser%2Fauth%2Fapple%2Fcallback&scope=email+name&response_type=code+id_token&response_mode=form_post})
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
    <asynchronous suspension>
    #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
    #3      SignInWithApple._signInWithAppleAndroid (package:sign_in_with_apple/src/sign_in_with_apple.dart:231:34)
    #4      SignInWithApple.getAppleIDCredential (package:sign_in_with_apple/src/sign_in_with_apple.dart:107:14)
    #5      _RegisterWidgetState.buildRegisterButtons.<anonymous closure> (package:example/widgets/profile/register/register_widget.dart:219:56)
    #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
    #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
    #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
    #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
    #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
    #11     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
    #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
    #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
    #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
    #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
    #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
    #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
    #18     _rootRunUnary (dart:async/zone.dart:1196:13)
    #19     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
    #21     _invoke1 (dart:ui/hooks.dart:275:10)
    #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
```

i have added the following to my manifest
```xml
<activity
android:name="com.aboutyou.dart_packages.sign_in_with_apple.SignInWithAppleCallback"
            android:exported="true"
            >
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="signinwithapple" />
                <data android:path="callback" />
            </intent-filter>
        </activity>
```

i have migrated to androidx
flutter version: 1.17.1
sign_in_with_apple version: 2.3.0

i have checked #73 and didn't get an answer
the exception happens here https://github.com/aboutyou/dart_packages/blob/master/packages/sign_in_with_apple/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt#L63

**Comment by HenriBeck** [comment]
Hey @Dreamersoul,

Thanks for reporting. You could please post the output of `flutter doctor -v` and also the `adb logcat` output here?

**Comment by Dreamersoul** [comment]
hey thank you for the response 
`flutter doctor -v` output:
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.6 18G4032, locale en-KW)
    • Flutter version 1.17.1 at /Users/Hamad/Development/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Hamad/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```

adb logcat
```bash
2020-05-26 17:34:59.876 8471-8588/com.example.app I/flutter: Transition { currentState: LoadingAnnouncements, event: Instance of 'LoadAnnouncements', nextState: LoadedAnnouncements }
2020-05-26 17:35:02.554 8471-8564/com.example.app V/FA: Inactivity, disconnecting from the service
2020-05-26 17:35:56.744 8471-8588/com.example.app E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(MISSING_ACTIVITY, Plugin is not attached to an activity, {url: https://appleid.apple.com/auth/authorize?client_id=com.example.app&redirect_uri=https%3A%2F%2Fexample.herokuapp.com%2Fuser%2Fauth%2Fapple%2Fcallback&scope=email+name&response_type=code+id_token&response_mode=form_post})
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
    <asynchronous suspension>
    #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
    #3      SignInWithApple._signInWithAppleAndroid (package:sign_in_with_apple/src/sign_in_with_apple.dart:231:34)
    #4      SignInWithApple.getAppleIDCredential (package:sign_in_with_apple/src/sign_in_with_apple.dart:107:14)
    #5      _RegisterWidgetState.buildRegisterButtons.<anonymous closure> (package:example/widgets/profile/register/register_widget.dart:219:56)
    #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
    #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
    #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
    #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
    #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
    #11     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
    #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
    #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
    #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
    #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
    #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
    #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
    #18     _rootRunUnary (dart:async/zone.dart:1196:13)
    #19     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
    #21     _invoke1 (dart:ui/hooks.dart:275:10)
    #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
```

here is my main activity which registers your plugin when i checked:

```kotlin
package com.phinests.clientapp

import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}
```

**Comment by HenriBeck** [comment]
Potentially two things:
```
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
```
this part of the code is not needed anymore. Manual plugin registration shouldn't be done anymore: https://github.com/flutter/flutter/issues/50004#issuecomment-597879208

**Comment by Dreamersoul** [comment]
thank you, i don't know how i missed this change! the error doesn't show up now!

**Comment by HenriBeck** [comment]
No worries, we had the same issue. For us also the plugins got registered twice, which sometimes does create some issues

**Comment by jaggernod** [comment]
@HenriBeck I have the same problem, and it is exactly because I'm using Android Embedding v1 (AEv1).
The issue is that we cannot change now to Android Embedding v2 (AEv2) at this moment. 

I see that in the current master (0c1c4b8620ae8f4bc948668595091dba9de2ce7a) you still support AEv1 with `registerWith` but then this will always fail as AEv1 does not notify `ActivityAware` interface methods. 
So then `binding?.activity` will always return `null`

Will this be likely be amended?

**Comment by HenriBeck** [comment]
@jaggernod I guess we can add support for it, would you be able to look into it? We might not get to this before next week.

Usually, nothing should prevent you from upgrading as it is backward compatible, so plugins that don't support it (yet hopefully) still work.

**Comment by jaggernod** [comment]
Sure, I can find some time to create a PR soon
